/** Aura Alpha dark theme — shared constants */
export const theme = {
  bg: '#0D1117',
  surface: '#161B22',
  surfaceAlt: '#1C2128',
  border: '#30363D',
  text: '#E6EDF3',
  textMuted: '#8B949E',
  green: '#3FB950',
  red: '#F85149',
  amber: '#D29922',
  blue: '#58A6FF',
  purple: '#BC8CFF',
  font: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Plus Jakarta Sans', sans-serif",
  mono: "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace",
};

/** Reusable inline style fragments */
export const styles = {
  page: {
    minHeight: '100vh',
    background: theme.bg,
    color: theme.text,
    fontFamily: theme.font,
    padding: '24px 32px',
  },
  card: {
    background: theme.surface,
    border: `1px solid ${theme.border}`,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    background: theme.surfaceAlt,
    border: `1px solid ${theme.border}`,
    borderRadius: 8,
    color: theme.text,
    fontFamily: theme.font,
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
  },
  inputFocus: {
    borderColor: theme.blue,
  },
  label: {
    display: 'block',
    fontSize: 13,
    color: theme.textMuted,
    marginBottom: 6,
    fontWeight: 500,
  },
  button: {
    padding: '10px 20px',
    background: theme.blue,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: theme.font,
    transition: 'opacity 0.2s',
  },
  buttonDanger: {
    padding: '10px 20px',
    background: theme.red,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: theme.font,
    transition: 'opacity 0.2s',
  },
  buttonSecondary: {
    padding: '10px 20px',
    background: 'transparent',
    color: theme.textMuted,
    border: `1px solid ${theme.border}`,
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: theme.font,
    transition: 'all 0.2s',
  },
  badge: (color) => ({
    display: 'inline-block',
    padding: '3px 10px',
    borderRadius: 99,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    background: color + '1A',
    color: color,
  }),
  dot: (color) => ({
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: color,
    display: 'inline-block',
    flexShrink: 0,
  }),
  h1: {
    fontSize: 28,
    fontWeight: 600,
    letterSpacing: -0.5,
    margin: 0,
  },
  h2: {
    fontSize: 18,
    fontWeight: 600,
    margin: 0,
  },
  subtitle: {
    fontSize: 14,
    color: theme.textMuted,
    margin: '4px 0 0',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 12,
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: 12,
  },
  flexRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  flexBetween: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldGroup: {
    marginBottom: 16,
  },
};
